default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: localhost
  pool: 5

development:
  <<: *default
  database: devisegem_development

test:
  <<: *default
  database: devisegem_test

production:
  <<: *default
  database: devisegem_production
  username: delivery-service
  password: <%= ENV['DELIVERY-SERVICE_DATABASE_PASSWORD'] %>
